// Dados das alíquotas de ICMS por estado
export const dadosICMS = [
  { id: "AC", estado: "Acre", aliquotaInterna: 17, aliquotaInterestadual: { sul_sudeste: 7, outros: 12 } },
  { id: "AL", estado: "Alagoas", aliquotaInterna: 17, aliquotaInterestadual: { sul_sudeste: 7, outros: 12 } },
  { id: "AM", estado: "Amazonas", aliquotaInterna: 18, aliquotaInterestadual: { sul_sudeste: 7, outros: 12 } },
  { id: "AP", estado: "Amapá", aliquotaInterna: 18, aliquotaInterestadual: { sul_sudeste: 7, outros: 12 } },
  { id: "BA", estado: "Bahia", aliquotaInterna: 18, aliquotaInterestadual: { sul_sudeste: 7, outros: 12 } },
  { id: "CE", estado: "Ceará", aliquotaInterna: 18, aliquotaInterestadual: { sul_sudeste: 7, outros: 12 } },
  { id: "DF", estado: "Distrito Federal", aliquotaInterna: 18, aliquotaInterestadual: { sul_sudeste: 7, outros: 12 } },
  { id: "ES", estado: "Espírito Santo", aliquotaInterna: 17, aliquotaInterestadual: { sul_sudeste: 7, outros: 12 } },
  { id: "GO", estado: "Goiás", aliquotaInterna: 17, aliquotaInterestadual: { sul_sudeste: 7, outros: 12 } },
  { id: "MA", estado: "Maranhão", aliquotaInterna: 18, aliquotaInterestadual: { sul_sudeste: 7, outros: 12 } },
  { id: "MG", estado: "Minas Gerais", aliquotaInterna: 18, aliquotaInterestadual: { sul_sudeste: 12, outros: 12 } },
  {
    id: "MS",
    estado: "Mato Grosso do Sul",
    aliquotaInterna: 17,
    aliquotaInterestadual: { sul_sudeste: 7, outros: 12 },
  },
  { id: "MT", estado: "Mato Grosso", aliquotaInterna: 17, aliquotaInterestadual: { sul_sudeste: 7, outros: 12 } },
  { id: "PA", estado: "Pará", aliquotaInterna: 17, aliquotaInterestadual: { sul_sudeste: 7, outros: 12 } },
  { id: "PB", estado: "Paraíba", aliquotaInterna: 18, aliquotaInterestadual: { sul_sudeste: 7, outros: 12 } },
  { id: "PE", estado: "Pernambuco", aliquotaInterna: 18, aliquotaInterestadual: { sul_sudeste: 7, outros: 12 } },
  { id: "PI", estado: "Piauí", aliquotaInterna: 18, aliquotaInterestadual: { sul_sudeste: 7, outros: 12 } },
  { id: "PR", estado: "Paraná", aliquotaInterna: 18, aliquotaInterestadual: { sul_sudeste: 12, outros: 12 } },
  { id: "RJ", estado: "Rio de Janeiro", aliquotaInterna: 20, aliquotaInterestadual: { sul_sudeste: 12, outros: 12 } },
  {
    id: "RN",
    estado: "Rio Grande do Norte",
    aliquotaInterna: 18,
    aliquotaInterestadual: { sul_sudeste: 7, outros: 12 },
  },
  { id: "RO", estado: "Rondônia", aliquotaInterna: 17.5, aliquotaInterestadual: { sul_sudeste: 7, outros: 12 } },
  { id: "RR", estado: "Roraima", aliquotaInterna: 17, aliquotaInterestadual: { sul_sudeste: 7, outros: 12 } },
  {
    id: "RS",
    estado: "Rio Grande do Sul",
    aliquotaInterna: 17,
    aliquotaInterestadual: { sul_sudeste: 12, outros: 12 },
  },
  { id: "SC", estado: "Santa Catarina", aliquotaInterna: 17, aliquotaInterestadual: { sul_sudeste: 12, outros: 12 } },
  { id: "SE", estado: "Sergipe", aliquotaInterna: 18, aliquotaInterestadual: { sul_sudeste: 7, outros: 12 } },
  { id: "SP", estado: "São Paulo", aliquotaInterna: 18, aliquotaInterestadual: { sul_sudeste: 12, outros: 12 } },
  { id: "TO", estado: "Tocantins", aliquotaInterna: 18, aliquotaInterestadual: { sul_sudeste: 7, outros: 12 } },
]

// Dados de produtos com alíquotas especiais
export const produtosEspeciais = [
  {
    nome: "Combustíveis",
    estados: [
      { id: "SP", estado: "São Paulo", aliquota: 25 },
      { id: "RJ", estado: "Rio de Janeiro", aliquota: 32 },
      { id: "MG", estado: "Minas Gerais", aliquota: 27 },
      { id: "RS", estado: "Rio Grande do Sul", aliquota: 25 },
      { id: "PR", estado: "Paraná", aliquota: 29 },
      { id: "SC", estado: "Santa Catarina", aliquota: 25 },
      { id: "BA", estado: "Bahia", aliquota: 28 },
      { id: "GO", estado: "Goiás", aliquota: 25 },
      { id: "DF", estado: "Distrito Federal", aliquota: 28 },
      { id: "MT", estado: "Mato Grosso", aliquota: 25 },
      { id: "MS", estado: "Mato Grosso do Sul", aliquota: 25 },
      { id: "ES", estado: "Espírito Santo", aliquota: 27 },
      { id: "PE", estado: "Pernambuco", aliquota: 29 },
      { id: "CE", estado: "Ceará", aliquota: 29 },
      { id: "PA", estado: "Pará", aliquota: 25 },
      { id: "MA", estado: "Maranhão", aliquota: 25 },
      { id: "PB", estado: "Paraíba", aliquota: 25 },
      { id: "PI", estado: "Piauí", aliquota: 25 },
      { id: "RN", estado: "Rio Grande do Norte", aliquota: 25 },
      { id: "AL", estado: "Alagoas", aliquota: 27 },
      { id: "SE", estado: "Sergipe", aliquota: 27 },
      { id: "AM", estado: "Amazonas", aliquota: 25 },
      { id: "RO", estado: "Rondônia", aliquota: 25 },
      { id: "TO", estado: "Tocantins", aliquota: 25 },
      { id: "AC", estado: "Acre", aliquota: 25 },
      { id: "AP", estado: "Amapá", aliquota: 25 },
      { id: "RR", estado: "Roraima", aliquota: 25 },
    ],
  },
  {
    nome: "Energia Elétrica",
    estados: [
      { id: "SP", estado: "São Paulo", aliquota: 25 },
      { id: "RJ", estado: "Rio de Janeiro", aliquota: 30 },
      { id: "MG", estado: "Minas Gerais", aliquota: 30 },
      { id: "RS", estado: "Rio Grande do Sul", aliquota: 25 },
      { id: "PR", estado: "Paraná", aliquota: 29 },
      { id: "SC", estado: "Santa Catarina", aliquota: 25 },
      { id: "BA", estado: "Bahia", aliquota: 27 },
      { id: "GO", estado: "Goiás", aliquota: 29 },
      { id: "DF", estado: "Distrito Federal", aliquota: 25 },
      { id: "MT", estado: "Mato Grosso", aliquota: 25 },
      { id: "MS", estado: "Mato Grosso do Sul", aliquota: 25 },
      { id: "ES", estado: "Espírito Santo", aliquota: 25 },
      { id: "PE", estado: "Pernambuco", aliquota: 25 },
      { id: "CE", estado: "Ceará", aliquota: 27 },
      { id: "PA", estado: "Pará", aliquota: 25 },
      { id: "MA", estado: "Maranhão", aliquota: 25 },
      { id: "PB", estado: "Paraíba", aliquota: 25 },
      { id: "PI", estado: "Piauí", aliquota: 25 },
      { id: "RN", estado: "Rio Grande do Norte", aliquota: 25 },
      { id: "AL", estado: "Alagoas", aliquota: 25 },
      { id: "SE", estado: "Sergipe", aliquota: 25 },
      { id: "AM", estado: "Amazonas", aliquota: 25 },
      { id: "RO", estado: "Rondônia", aliquota: 25 },
      { id: "TO", estado: "Tocantins", aliquota: 25 },
      { id: "AC", estado: "Acre", aliquota: 25 },
      { id: "AP", estado: "Amapá", aliquota: 25 },
      { id: "RR", estado: "Roraima", aliquota: 25 },
    ],
  },
  {
    nome: "Telecomunicações",
    estados: [
      { id: "SP", estado: "São Paulo", aliquota: 25 },
      { id: "RJ", estado: "Rio de Janeiro", aliquota: 29 },
      { id: "MG", estado: "Minas Gerais", aliquota: 27 },
      { id: "RS", estado: "Rio Grande do Sul", aliquota: 30 },
      { id: "PR", estado: "Paraná", aliquota: 29 },
      { id: "SC", estado: "Santa Catarina", aliquota: 25 },
      { id: "BA", estado: "Bahia", aliquota: 27 },
      { id: "GO", estado: "Goiás", aliquota: 29 },
      { id: "DF", estado: "Distrito Federal", aliquota: 28 },
      { id: "MT", estado: "Mato Grosso", aliquota: 25 },
      { id: "MS", estado: "Mato Grosso do Sul", aliquota: 25 },
      { id: "ES", estado: "Espírito Santo", aliquota: 25 },
      { id: "PE", estado: "Pernambuco", aliquota: 25 },
      { id: "CE", estado: "Ceará", aliquota: 25 },
      { id: "PA", estado: "Pará", aliquota: 25 },
      { id: "MA", estado: "Maranhão", aliquota: 25 },
      { id: "PB", estado: "Paraíba", aliquota: 25 },
      { id: "PI", estado: "Piauí", aliquota: 25 },
      { id: "RN", estado: "Rio Grande do Norte", aliquota: 25 },
      { id: "AL", estado: "Alagoas", aliquota: 25 },
      { id: "SE", estado: "Sergipe", aliquota: 25 },
      { id: "AM", estado: "Amazonas", aliquota: 25 },
      { id: "RO", estado: "Rondônia", aliquota: 25 },
      { id: "TO", estado: "Tocantins", aliquota: 25 },
      { id: "AC", estado: "Acre", aliquota: 25 },
      { id: "AP", estado: "Amapá", aliquota: 25 },
      { id: "RR", estado: "Roraima", aliquota: 25 },
    ],
  },
  {
    nome: "Bebidas Alcoólicas",
    estados: [
      { id: "SP", estado: "São Paulo", aliquota: 25 },
      { id: "RJ", estado: "Rio de Janeiro", aliquota: 25 },
      { id: "MG", estado: "Minas Gerais", aliquota: 25 },
      { id: "RS", estado: "Rio Grande do Sul", aliquota: 25 },
      { id: "PR", estado: "Paraná", aliquota: 29 },
      { id: "SC", estado: "Santa Catarina", aliquota: 25 },
      { id: "BA", estado: "Bahia", aliquota: 25 },
      { id: "GO", estado: "Goiás", aliquota: 25 },
      { id: "DF", estado: "Distrito Federal", aliquota: 25 },
      { id: "MT", estado: "Mato Grosso", aliquota: 25 },
      { id: "MS", estado: "Mato Grosso do Sul", aliquota: 25 },
      { id: "ES", estado: "Espírito Santo", aliquota: 25 },
      { id: "PE", estado: "Pernambuco", aliquota: 25 },
      { id: "CE", estado: "Ceará", aliquota: 25 },
      { id: "PA", estado: "Pará", aliquota: 25 },
      { id: "MA", estado: "Maranhão", aliquota: 25 },
      { id: "PB", estado: "Paraíba", aliquota: 25 },
      { id: "PI", estado: "Piauí", aliquota: 25 },
      { id: "RN", estado: "Rio Grande do Norte", aliquota: 25 },
      { id: "AL", estado: "Alagoas", aliquota: 25 },
      { id: "SE", estado: "Sergipe", aliquota: 25 },
      { id: "AM", estado: "Amazonas", aliquota: 25 },
      { id: "RO", estado: "Rondônia", aliquota: 25 },
      { id: "TO", estado: "Tocantins", aliquota: 25 },
      { id: "AC", estado: "Acre", aliquota: 25 },
      { id: "AP", estado: "Amapá", aliquota: 25 },
      { id: "RR", estado: "Roraima", aliquota: 25 },
    ],
  },
]

